/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'me': RouteRecordInfo<'me', '/me', Record<never, never>, Record<never, never>>,
    'collect': RouteRecordInfo<'collect', '/me/collect', Record<never, never>, Record<never, never>>,
    'search': RouteRecordInfo<'search', '/search', Record<never, never>, Record<never, never>>,
    'searchpage': RouteRecordInfo<'searchpage', '/search/searchpage', Record<never, never>, Record<never, never>>,
    'tree': RouteRecordInfo<'tree', '/tree', Record<never, never>, Record<never, never>>,
    'treeDetail': RouteRecordInfo<'treeDetail', '/tree/treedetail', Record<never, never>, Record<never, never>>,
    'web': RouteRecordInfo<'web', '/web', Record<never, never>, Record<never, never>>,
  }
}
